-- SIGO System - Supabase Migration Script 04 (RH)

CREATE TABLE IF NOT EXISTS employees (
  id TEXT PRIMARY KEY,
  company_id TEXT,
  name TEXT NOT NULL,
  role TEXT,
  admission_date DATE,
  salary NUMERIC DEFAULT 0,
  payment_type TEXT,
  cpf TEXT,
  rg_number TEXT,
  rg_agency TEXT,
  rg_issuer TEXT,
  rg_state TEXT,
  birth_date DATE,
  birth_place TEXT,
  birth_state TEXT,
  work_booklet_number TEXT,
  work_booklet_series TEXT,
  pis TEXT,
  phone TEXT,
  mobile TEXT,
  email TEXT,
  voter_id_number TEXT,
  voter_zone TEXT,
  voter_section TEXT,
  father_name TEXT,
  mother_name TEXT,
  spouse_name TEXT,
  dependents JSONB DEFAULT '[]',
  address_logradouro TEXT,
  address_number TEXT,
  address_complement TEXT,
  address_neighborhood TEXT,
  address_city TEXT,
  address_zip_code TEXT,
  address_state TEXT,
  contract_id TEXT,
  status TEXT DEFAULT 'active',
  dismissal_date DATE,
  commuter_benefits BOOLEAN DEFAULT false,
  commuter_value1 NUMERIC,
  commuter_city1 TEXT,
  commuter_value2 NUMERIC,
  commuter_city2 TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON employees FOR ALL USING (true) WITH CHECK (true);
