-- Script para atualizar a tabela de equipamentos e garantir o salvamento das informações

-- Tabela principal: equipments
CREATE TABLE IF NOT EXISTS equipments (
  id uuid PRIMARY KEY,
  company_id text,
  contract_id uuid,
  code text,
  name text NOT NULL,
  type text,
  brand text,
  model text,
  year integer,
  situation text,
  plate text,
  origin text,
  category text,
  owner_name text,
  owner_cnpj text,
  entry_date text,
  exit_date text,
  in_maintenance boolean,
  maintenance_entry_date text,
  maintenance_exit_date text,
  maintenance_type text,
  charges_percentage numeric,
  overtime_percentage numeric,
  measurement_unit text,
  current_reading numeric,
  contracted_price numeric,
  monthly_price numeric,
  observations text,
  custom_fields jsonb,
  photos jsonb,
  history jsonb,
  measurements jsonb,
  team text
);

ALTER TABLE equipments
ADD COLUMN IF NOT EXISTS code text,
ADD COLUMN IF NOT EXISTS in_maintenance boolean,
ADD COLUMN IF NOT EXISTS maintenance_entry_date text,
ADD COLUMN IF NOT EXISTS maintenance_exit_date text,
ADD COLUMN IF NOT EXISTS maintenance_type text,
ADD COLUMN IF NOT EXISTS charges_percentage numeric,
ADD COLUMN IF NOT EXISTS overtime_percentage numeric,
ADD COLUMN IF NOT EXISTS measurement_unit text,
ADD COLUMN IF NOT EXISTS current_reading numeric,
ADD COLUMN IF NOT EXISTS contracted_price numeric,
ADD COLUMN IF NOT EXISTS monthly_price numeric,
ADD COLUMN IF NOT EXISTS observations text,
ADD COLUMN IF NOT EXISTS custom_fields jsonb,
ADD COLUMN IF NOT EXISTS photos jsonb,
ADD COLUMN IF NOT EXISTS history jsonb,
ADD COLUMN IF NOT EXISTS measurements jsonb,
ADD COLUMN IF NOT EXISTS team text,
ADD COLUMN IF NOT EXISTS brand text,
ADD COLUMN IF NOT EXISTS year integer,
ADD COLUMN IF NOT EXISTS situation text;

-- Tabela fallback: controller_equipments (se o cliente estiver usando essa ao invés de equipments)
CREATE TABLE IF NOT EXISTS controller_equipments (
  id uuid PRIMARY KEY,
  company_id text,
  contract_id uuid,
  code text,
  name text NOT NULL,
  type text,
  brand text,
  model text,
  year integer,
  situation text,
  plate text,
  origin text,
  category text,
  owner_name text,
  owner_cnpj text,
  entry_date text,
  exit_date text,
  in_maintenance boolean,
  maintenance_entry_date text,
  maintenance_exit_date text,
  maintenance_type text,
  charges_percentage numeric,
  overtime_percentage numeric,
  measurement_unit text,
  current_reading numeric,
  contracted_price numeric,
  monthly_price numeric,
  observations text,
  custom_fields jsonb,
  photos jsonb,
  history jsonb,
  measurements jsonb,
  team text
);

ALTER TABLE controller_equipments
ADD COLUMN IF NOT EXISTS code text,
ADD COLUMN IF NOT EXISTS in_maintenance boolean,
ADD COLUMN IF NOT EXISTS maintenance_entry_date text,
ADD COLUMN IF NOT EXISTS maintenance_exit_date text,
ADD COLUMN IF NOT EXISTS maintenance_type text,
ADD COLUMN IF NOT EXISTS charges_percentage numeric,
ADD COLUMN IF NOT EXISTS overtime_percentage numeric,
ADD COLUMN IF NOT EXISTS measurement_unit text,
ADD COLUMN IF NOT EXISTS current_reading numeric,
ADD COLUMN IF NOT EXISTS contracted_price numeric,
ADD COLUMN IF NOT EXISTS monthly_price numeric,
ADD COLUMN IF NOT EXISTS observations text,
ADD COLUMN IF NOT EXISTS custom_fields jsonb,
ADD COLUMN IF NOT EXISTS photos jsonb,
ADD COLUMN IF NOT EXISTS history jsonb,
ADD COLUMN IF NOT EXISTS measurements jsonb,
ADD COLUMN IF NOT EXISTS team text,
ADD COLUMN IF NOT EXISTS brand text,
ADD COLUMN IF NOT EXISTS year integer,
ADD COLUMN IF NOT EXISTS situation text;

